[project]
name = "vvm-reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dask>=2025.10.0",
    "matplotlib>=3.10.7",
    "netcdf4>=1.7.3",
    "xarray>=2025.10.1",
]
